# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [11]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 7654 samples
Epoch 1/100
7654/7654 [==============================] - 1s 152us/sample - loss: 12181.2910
Epoch 2/100
7654/7654 [==============================] - 0s 54us/sample - loss: 386.8362
Epoch 3/100
7654/7654 [==============================] - 0s 54us/sample - loss: 372.7908
Epoch 4/100
7654/7654 [==============================] - 0s 53us/sample - loss: 354.8879
Epoch 5/100
7654/7654 [==============================] - 0s 53us/sample - loss: 334.3140
Epoch 6/100
7654/7654 [==============================] - 0s 56us/sample - loss: 311.1978
Epoch 7/100
7654/7654 [==============================] - 0s 55us/sample - loss: 286.4625
Epoch 8/100
7654/7654 [==============================] - 0s 56us/sample - loss: 260.4999
Epoch 9/100
7654/7654 [==============================] - 0s 56us/sample - loss: 234.3526
Epoch 10/100
7654/7654 [==============================] - 0s 57us/sample - loss: 207.1673
Epoch 11/100
7654/7654 [==============================] - 0s 55us/sample - loss: 179

7654/7654 [==============================] - 0s 53us/sample - loss: 26.6138
Epoch 93/100
7654/7654 [==============================] - 0s 50us/sample - loss: 26.4830
Epoch 94/100
7654/7654 [==============================] - 0s 51us/sample - loss: 27.2435
Epoch 95/100
7654/7654 [==============================] - 0s 50us/sample - loss: 26.9099
Epoch 96/100
7654/7654 [==============================] - 0s 52us/sample - loss: 26.7302
Epoch 97/100
7654/7654 [==============================] - 0s 60us/sample - loss: 26.6819
Epoch 98/100
7654/7654 [==============================] - 0s 52us/sample - loss: 26.2107
Epoch 99/100
7654/7654 [==============================] - 0s 52us/sample - loss: 27.1682
Epoch 100/100
7654/7654 [==============================] - 0s 54us/sample - loss: 26.7255


### Predicting the results of the Test set

In [12]:
ann.predict(X_test)

array([[430.89   ],
       [461.8732 ],
       [465.33667],
       ...,
       [472.58603],
       [439.47174],
       [458.6257 ]], dtype=float32)

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 3)
np.concatenate( (y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), axis = 1 )

array([[430.89 , 431.23 ],
       [461.873, 460.01 ],
       [465.337, 461.14 ],
       ...,
       [472.586, 473.26 ],
       [439.472, 438.   ],
       [458.626, 463.28 ]])